import { Kafka, Producer } from 'kafkajs';
import { promises as afs } from 'fs';
import * as fs from 'fs';
import { create } from 'domain';

const logsLocation = process.env.LOGS_FOLDER;

const kafka = new Kafka({
    clientId: `${process.env.KAFKA_CLIENT_ID}`,
    brokers: [`${process.env.KAFKA_BROKER}:${process.env.KAFKA_BROKER_PORT}`]
});

let producer: Producer;

const createProducer = async () => {
    while(true) {
        let producer = kafka.producer();
        try {
            await producer.connect();
            return producer;
        } catch(e) {
            console.log("Cannot connect to Kafka broker, retrying");
            await new Promise(r => setTimeout(r, 2000));
        }
    }
};

const waitOnProducer = async () => {
    while(true) {
        if(producer !== undefined)
            break;
        await new Promise(res => setTimeout(res, 1000));
    }
};

const uploadMissing = async() => {
    let files = await afs.readdir(logsLocation!);
    console.log(`Processing missing files: ${files.length}`);
    for(let file of files) {
        await fileCallback("change", file);
    }
};

const fileCallback = async (eventType: string, filename: string) => {
    await waitOnProducer();

    if(eventType !== "change")
        return;

    console.log(`Processing log ${filename}`);

    let filePath = `${logsLocation}/${filename}`;
    let file = await afs.readFile(filePath);

    console.log(`Sending ${filename} content to kafka`);

    await producer.send({
        topic: process.env.KAFKA_INGRESS_TOPIC!,
        messages: [
            {value: file}
        ],
    });

    console.log(`Deleting ${filename} log`);
    await afs.unlink(filePath);
};

const main = () => {
    console.log(`Starting nginx logs exporter.`);
    createProducer().then((res) => producer = res);

    // setup listener for logs folder with logs generated by nginx njs
    if(logsLocation === undefined) {
        console.error("Logs location path not defined, aborting");
        return;
    }
    uploadMissing().then();
    fs.watch(logsLocation, {
        persistent: true,
        recursive: false,
        encoding: "utf-8",
    }, fileCallback);
};

main();

export default { main };
